### ISSUE TITLE
Create a custom Thali PouchDB constructor utility

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#773]
## Problem: 
In order to use PouchDB against a local file (as opposed to a remote URL) in JXcore on mobile we need to set two options, one is called db and we have to set it to leveldown-mobile and the other is called prefix and it specifies what directory the DB's files are to be stored in. The prefix matters because on mobile there are only certain directories we can store things in.
   Everything was fine and good until PouchDB broke prefix badly in the last major release. In the old days prefix ONLY applied to local DBs. But now pouchDB applies prefix to both local DBs and to remote DBs. In other words if I set new PouchDB('foo', {prefix: '/bar'}) then PouchDB will try to create foo's files in the /bar directory. If I call new PouchDB('http://foo.com', {prefix: '/bar'}) then now it does something really bizarre like try to connect to the server /barhttp://foo.com or something like that. Bad. Bad. Bad.
  Now you may ask, who cares? Just make sure not to pass in prefix to PouchDB instances that use a URL. But it's not that simple. The problem is replication. When we replicate we MUST start by creating a var remotePouch = new PouchDB('http://foo.com', {stick in a bunch of ajax options to configure PSK and other stuff here}) in order to configure all of our network options correctly, set up PSK, etc. Then we take that object and we have to call remotePouch.replicate.to(foo). Where foo is the local dB name we are writing to. Now replicate.to() does take options but one of those options is not prefix. So how do we make sure that we read foo from the right directory?
 Historically we did this by telling people to use the defaults feature in PouchDB. This feature lets one set a number of default constructor options and when PouchDB creates a new instance of itself (for example, it will create a new instance of itself to represent foo above) it will use those defaults. So we would set prefix on the defaults and when PouchDB created a new instance of itself to represent foo it would automatically have the prefix. But if we use that feature now then it would break the HTTP URL since the default applies to all calls to new now, not just to local files.
  So how do we let people set the prefix just for local files and not for remote URLS?

## Solution: 
The solution is [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/8130305ed2a11afe9cb9acb8e80628870e4298cf/test/www/jxcore/lib/testUtils.js#L247). This is a function I wrote with the help of Nolan Lawson (it's really just stolen code from PouchDB) that wraps the constructor such that when the constructor creates a new version of itself if the version is for a local file then it will set the db to leveldown-mobile and the prefix to the right directory and if it is for a remote URL it does neither.
  But that function right now only exists in our test code. What we need to do is extract it from the test code and we need to update it so it takes two arguments. The first argument is the PouchDB object to be wrapped (no reason to make Thali itself dependent on any particular version of PouchDB) and the second argument is the defaultDirectory.
   I do not think we should build this into thaliManager. We should keep it as a stand alone utility because that way people can do other weird stuff with PouchDB and we won't break.

## Work Items: 
So please:
- [ ] Extract the function from the test file and move it into next generation as a utility function, please change the args as I discuss above
- [ ] Remove the test version completely and replace our call to it with the 'real' version (so our tests don't break)
- [ ] Add tests to our test infrastructure to make sure that the utility is working properly

**Comment by yaronyg** [comment]
The code is written and now he just needs the test.
